# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2023db1b800d51e28c8cec4360c02c41a80130531f541d74d1fa24425452083a9f4884a7f30edd178e60d191688a979019bb02c895da94c0fcf4a03e90029096

test:
  secret_key_base: bc373cd8c00f4a23194dbff5e3125d2cb0d7c8fd82af41f301d1af138bac2c6b551ad1eaea4e97f7a922176fd69ff94af99eb80cf916ca569997ae07e2567284

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
